apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fal18j070-python 
  janus-idp.io/tekton: fal18j070-python
  backstage.io/kubernetes-id: fal18j070-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fal18j070-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml